In [1]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

#Ignore Warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
iris = load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [3]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [4]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris["data"][0]

array([5.1, 3.5, 1.4, 0.2])

In [7]:
iris["target"][0]

0

In [8]:
X = iris["data"][:, 2:] #petal width and petal length
y = (iris["target"] == 2).astype(np.int) #1 for virginica and 0 for non-virginica

In [9]:
X[0:5]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2]])

In [10]:
y[0:5]

array([0, 0, 0, 0, 0])

In [11]:
print(f'''X Shape is : {X.shape}
Y Shape is : {y.shape}''')

X Shape is : (150, 2)
Y Shape is : (150,)


In [12]:
b0 = 0
b1 = 0
b2 = 0

In [13]:
pred0 = 1 / (1 + np.exp(-(b0 + b1 * X[0][0] + b2 * X[0][1])))
pred0

0.5

In [14]:
pred1 = 1 / (1 + np.exp(-(b0 + b1 * X[149][0] + b2 * X[149][1])))
pred1

0.5

For better predictions, we have to update `b` <br>
`b = b + alpha * (y - prediction) * prediction * (1 - prediction) * x`

In [17]:
alpha = 0.1
b0 = b0 + alpha * (y[1] - pred1) * pred1 * (1 - pred1) * 1
b1 = b1 + alpha * (y[1] - pred1) * pred1 * (1 - pred1) * X[1][0]
b2 = b2 + alpha * (y[1] - pred1) * pred1 * (1 - pred1) * X[1][1]

In [18]:
pred2 = 1 / (1 + np.exp(-(b0 + b1 * X[149][0] + b2 * X[149][1])))
pred2

0.4734624606323862

In [26]:
alpha = 0.1
b0 = b0 + alpha * (y[1] - pred2) * pred2 * (1 - pred2) * 1
b1 = b1 + alpha * (y[1] - pred2) * pred2 * (1 - pred2) * X[1][0]
b2 = b2 + alpha * (y[1] - pred2) * pred2 * (1 - pred2) * X[1][1]

In [21]:
pred3 = 1 / (1 + np.exp(-(b0 + b1 * X[1][0] + b2 * X[1][1])))
pred3

0.4817806564163542

In [22]:
alpha = 0.1
b0 = b0 + alpha * (y[149] - pred3) * pred3 * (1 - pred3) * 1
b1 = b1 + alpha * (y[149] - pred3) * pred3 * (1 - pred3) * X[149][0]
b2 = b2 + alpha * (y[149] - pred3) * pred3 * (1 - pred3) * X[149][1]

In [23]:
pred4 = 1 / (1 + np.exp(-(b0 + b1 * X[149][0] + b2 * X[149][1])))
pred4

0.546070369448201

In [28]:
print(f'''B0 {b0} 
B1 {b1}
B2 {b2}
''')

B0 -0.023168155112174127 
B1 0.015436224705627999
B2 0.016067619512774592



In [27]:
pred5 = 1 / (1 + np.exp(-(b0 + b1 * X[1][0] + b2 * X[1][1])))
pred5

0.5004140207499401